---
title: "Active learning mapping in Congo"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["default", "lucy", "middlebury-fonts", "themes/class1.css"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

## Background









A crop field in the congo 

-This project builds upon the work done on the Mapping Africa project. 
-The project seeks to implement the exsting Active Learning Framwork from Ghana to the Congo
-The project is computational powered by AWS (EC2 for compute and S3 for storage) and has a large human feedbackloop.There are four major mapping components: 
    1) image acquisition and pre-processing
    2) training data
    3) machine learning
    4) segmentation 











Above is the overal AOI 

---

## 1 image acquisition - Noah
  -The first stage is Image acquisition
  -This was completed using EC2 and Planet Scope Imagery.Planet Scope Satellites are box satellites provide high temporal and spatial resolution for cropland identification.
  - Two time frames:
     1) Dry season (December-February)
     2) Wet season (May - September)
  











Composite image on the right is growing season, and on the left is non-growing season.

---

## 2 Training data collection -Priyanka and Wei Hong















-The images were then process in Amazon EC2, 200 training sites were randomly selected from the AOIs.
-The sites are then stored in postgres. 












-Training site classfiers from the spatial collective in Africa access a OpenLayers.The classifiers from the -spatial collect work on creating training and validation data.


















-Settlement Locations (datafromHDX) and the buffer sights

 
 
 
--- 

##Machine learning/ (Future)
-Apart of future steps in mapping the cropland of congo
-In this stage the human / machine and machine connection is established 
-A "custom crowdsourcing platfrom" is created(Estes 8)

-This platfrom is called labeller wich is built around human assessors that complete tasks, includes building data for understanding accuracry and also data for tranning
- Mapper is established for classfication 










- Mapper is a random forest algorithm that has 80 trees

---

##Conclusion
-The final two steps are the active feedback loop and segmentation
-This segmentation (field segmentation) step is powered by a meanshift algorithm (Yizong Cheng 1995) and followed up by a accuracy assessment
-The challange of creating a automated system for cropland segmentaion in heavily forested and remote area
-Requires care towards accuarcy and limiting factors
    


---

##Thank you
 -Lyndon, Su and Lei

